### PR TITLE
Fix mouse pointer backdrop click

### LINKED ISSUE #357: Mouse swipe navigation closes the lightbox when closeOnBackdropClick is enabled
### Describe the bug

When the `closeOnBackdropClick` option is enabled, swiping on the black background outside an image closes the lightbox.

See https://github.com/igordanchenko/yet-another-react-lightbox/discussions/354#discussioncomment-13155687 for details.

### Expected behavior

Lightbox should not close in this case.

### How to reproduce

```tsx
<Lightbox
  open={open}
  close={() => setOpen(false)}
  slides={slides}
  controller={{ closeOnBackdropClick: true }}
/>
```

### Screenshots / Logs

Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by aichisuan**
### Description

Fix #357 

### Checklist

- [x] I have followed the 'Sending a Pull Request' section of the [contributing guide](https://github.com/igordanchenko/yet-another-react-lightbox/blob/main/CONTRIBUTING.md#sending-a-pull-request)

### CODE REVIEW

File: dev/App.tsx [hunk 1]
```diff
@@ -27,6 +27,9 @@ export default function App() {
         open={open}
         close={() => setOpen(false)}
         slides={slides}
+        controller={{
+          closeOnBackdropClick: true,
+        }}
```
Comment (igordanchenko) [inline dev/App.tsx:32]: There is no need to commit this change in the demo app. Please remove.

File: src/modules/Carousel.tsx [hunk 2]
```diff
@@ -37,12 +37,12 @@ function CarouselSlide({ slide, offset }: CarouselSlideProps) {
...
 
   const { currentIndex } = useLightboxState();
-  const { slideRect, close, focus } = useController();
+  const { slideRect, focus } = useController();
   const {
     render,
     carousel: { imageFit, imageProps },
     on: { click: onClick },
-    controller: { closeOnBackdropClick },
+    // controller: { closeOnBackdropClick },
```
Comment (igordanchenko) [inline src/modules/Carousel.tsx:45]: No need to keep the unused code in comments. Please delete the code that is no longer in use.

File: src/modules/Carousel.tsx [hunk 3]
```diff
@@ -81,24 +81,23 @@ function CarouselSlide({ slide, offset }: CarouselSlideProps) {
...
+  //     target &&
+  //     container &&
+  //     (target === container ||
+  //       // detect Zoom and Video wrappers
+  //       (Array.from(container.children).find((x) => x === target) &&
+  //         target.classList.contains(cssClass(CLASS_SLIDE_WRAPPER))))
+  //   ) {
+  //     close();
+  //   }
+  // };
```
Comment (igordanchenko) [inline src/modules/Carousel.tsx:98]: No need to keep the unused code in comments. Please delete the code that is no longer in use.

File: src/modules/Carousel.tsx [hunk 4]
```diff
@@ -107,7 +106,7 @@ function CarouselSlide({ slide, offset }: CarouselSlideProps) {
         cssClass(CLASS_FLEX_CENTER),
       )}
       {...makeInertWhen(offscreen)}
-      onClick={handleBackdropClick}
+      // onClick={handleBackdropClick}
```
Comment (igordanchenko) [inline src/modules/Carousel.tsx:109]: No need to keep the unused code in comments. Please delete the code that is no longer in use.

File: src/modules/Controller/usePointerSwipe.ts [hunk 5]
```diff
@@ -14,7 +16,13 @@ enum Gesture {
 const SWIPE_THRESHOLD = 30;
 
 export function usePointerSwipe<T extends Element = Element>(
-  { disableSwipeNavigation }: ControllerSettings,
+  {
+    disableSwipeNavigation,
+    closeOnBackdropClick,
+    onClose,
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:22]: Let's add the `onClose` callback as the last argument of the function after the `onPullCancel`.

File: src/modules/Controller/usePointerSwipe.ts [hunk 6]
```diff
@@ -36,6 +44,10 @@ export function usePointerSwipe<T extends Element = Element>(
   const startTime = React.useRef<number>(0);
   const gesture = React.useRef(Gesture.NONE);
 
+  const startClickTime = React.useRef<number>(0);
+  const isClick = React.useRef(false);
+  const startPosition = React.useRef<{ x: number; y: number } | null>(null);
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:49]: I'm pretty sure these variables are redundant and can be eliminated. Please see my other comments below. If you need to access the corresponding pointer event from the `onPointerDown`, then you can find it in the `pointers` array.

File: src/modules/Controller/usePointerSwipe.ts [hunk 7]
```diff
@@ -61,35 +73,52 @@ export function usePointerSwipe<T extends Element = Element>(
...
-        } else {
-          onSwipeCancel(currentOffset);
-        }
-      } else if (gesture.current === Gesture.PULL) {
-        if (exceedsPullThreshold(currentOffset, 2 * SWIPE_THRESHOLD)) {
-          onPullFinish(currentOffset, duration);
-        } else {
-          onPullCancel(currentOffset);
+    if (pointers.current.find((x) => x.pointerId === event.pointerId)) {
+      const clickDuration = Date.now() - startClickTime.current;
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:87]: Why do we need to track click duration and limit it to 300 milliseconds? For example, if I click the "Prev" or "Next" button, hold the mouse for several seconds, and then release it, it still registers as a click.

File: src/modules/Controller/usePointerSwipe.ts [hunk 8]
```diff
@@ -61,35 +73,52 @@ export function usePointerSwipe<T extends Element = Element>(
...
+      // Handle click events
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:88]: Let's move the click handling functionality to the `else` section of the `if (activePointer.current === event.pointerId)` block so that swipe and pull gestures get handled first.

File: src/modules/Controller/usePointerSwipe.ts [hunk 9]
```diff
@@ -61,35 +73,52 @@ export function usePointerSwipe<T extends Element = Element>(
...
+      if (isClick.current && clickDuration < 300) {
+        const target = event.target as HTMLElement;
+        if (closeOnBackdropClick && target && target.classList.contains(cssClass(CLASS_SLIDE_WRAPPER))) {
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:91]: please add `|| target.classList.contains(cssClass("slide"))` - that's the use when neither Zoom nor Video plugins are enabled.

File: src/modules/Controller/usePointerSwipe.ts [hunk 10]
```diff
@@ -115,6 +144,15 @@ export function usePointerSwipe<T extends Element = Element>(
       const deltaX = event.clientX - pointer.clientX;
       const deltaY = event.clientY - pointer.clientY;
 
+      // Check whether it exceeds the click threshold
```
Comment (igordanchenko) [inline src/modules/Controller/usePointerSwipe.ts:147]: Why do we need to track distance? For example, if I click a regular button and move the mouse pointer 30 or 50 pixels while over the button, it still registers as a click.

File: src/modules/Controller/usePointerSwipe.ts (hunk 7 above)
Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts:87]: Yes, but we filtered it in `onPointerUp`. If the mouse is held down for a few seconds, I might think that the user behavior is not that the user needs to click to close the mask.

Comment (igordanchenko) [reply src/modules/Controller/usePointerSwipe.ts:87]: I disagree. There is no 300ms threshold for typical click event (unlike double click), so I see no reason to implement it here.

File: src/modules/Controller/usePointerSwipe.ts (hunk 6 above)
Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts:49]: I think this is not a strict click event. It is necessary to judge the progress of the next step before it can be considered a click event, so we need to save part of the state of the previous step. Do you have a better solution?

File: src/modules/Controller/usePointerSwipe.ts (hunk 7 above)
Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts:87]: Do you mean we remove this judgment?

Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts:87]: Maybe my understanding is wrong, I removed this thing

File: src/modules/Controller/usePointerSwipe.ts (hunk 6 above)
Comment (igordanchenko) [reply src/modules/Controller/usePointerSwipe.ts]: I’m pretty sure we can identify click event in the `onPointerUp` callback using the following criteria:
- `onPointerUp` event target is the same backdrop element as in the corresponding `onPointerDown` event (the corresponding `onPointerDown` event is saved in the `pointers` array)
- it’s not a swipe gesture
- It’s not a pull up / pull down gesture

Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts]: Yes, after I read your code carefully, I found that I did a lot of unnecessary operations. I resubmitted this submission, you refresh it and see that it is indeed as you said. We only need to add a simple judgment。

File: src/modules/Controller/usePointerSwipe.ts (hunk 10 above)
Comment (aichisuan) [reply src/modules/Controller/usePointerSwipe.ts]: Yes, I understand what you mean. I added these judgments because I am not familiar with your code logic. I resubmitted the code. You can refresh and watch it. It doesn't seem to change much. I just added a judgment.
